on:
  release:
    branches: [ master-jun2020 ]
    tags: [ devlabs-release-* ]

name: Build Release
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2     
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo linux-386
        echo Test multi-line script line 1
        echo Test multi-line script line 2
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GOARCH: "386"
        GOOS: linux
        EXTRA_FILES: "klar LICENSE"
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo linux-amd64
        echo Test multi-line script line 1
        echo Test multi-line script line 2
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GOARCH: amd64
        GOOS: linux
        EXTRA_FILES: "klar LICENSE"
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo darwin-amd64
        echo Test multi-line script line 1
        echo Test multi-line script line 2
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GOARCH: amd64
        GOOS: darwin
        EXTRA_FILES: "klar LICENSE"


